/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * RAG Corp API
 * OpenAPI spec version: 0.1.0
 */
export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export interface QueryReq {
  query: string;
  top_k?: number;
}

export interface Match {
  chunk_id: string;
  content: string;
  document_id: string;
  score: number;
}

export interface QueryRes {
  matches: Match[];
}

export interface IngestTextRes {
  chunks: number;
  document_id: string;
}

export type IngestTextReqSource = string | null;

export type IngestTextReqMetadata = { [key: string]: unknown };

export interface IngestTextReq {
  metadata?: IngestTextReqMetadata;
  source?: IngestTextReqSource;
  text: string;
  title: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}



/**
 * @summary Ingest Text
 */
export type ingestTextV1IngestTextPostResponse = {
  data: IngestTextRes;
  status: number;
}

export const getIngestTextV1IngestTextPostUrl = () => {


  return `/v1/ingest/text`
}

export const ingestTextV1IngestTextPost = async (ingestTextReq: IngestTextReq, options?: RequestInit): Promise<ingestTextV1IngestTextPostResponse> => {
  const res = await fetch(getIngestTextV1IngestTextPostUrl(),
  {      
    ...options,
    method: 'POST',
    body: JSON.stringify(
      ingestTextReq,)
  }

  )
  const data = await res.json()

  return { status: res.status, data }
}


/**
 * @summary Query
 */
export type queryV1QueryPostResponse = {
  data: QueryRes;
  status: number;
}

export const getQueryV1QueryPostUrl = () => {


  return `/v1/query`
}

export const queryV1QueryPost = async (queryReq: QueryReq, options?: RequestInit): Promise<queryV1QueryPostResponse> => {
  const res = await fetch(getQueryV1QueryPostUrl(),
  {      
    ...options,
    method: 'POST',
    body: JSON.stringify(
      queryReq,)
  }

  )
  const data = await res.json()

  return { status: res.status, data }
}


/**
 * @summary Healthz
 */
export type healthzHealthzGetResponse = {
  data: unknown;
  status: number;
}

export const getHealthzHealthzGetUrl = () => {


  return `/healthz`
}

export const healthzHealthzGet = async ( options?: RequestInit): Promise<healthzHealthzGetResponse> => {
  const res = await fetch(getHealthzHealthzGetUrl(),
  {      
    ...options,
    method: 'GET'
    
  }

  )
  const data = await res.json()

  return { status: res.status, data }
}


